version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: investments-test
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: investments
          POSTGRES_DB: investments-test
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: investments-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        key: investments-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:schema:load --trace && bundle exec rake db:migrate

      - run:
          name: Run tests
          command: bundle exec rake

  deploy:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy Investments-Qa

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

