version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: investments-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        key: investments-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake