development:
  adapter: postgresql
  encoding: unicode
  database: investments_development
  pool: 5
  username: investments
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: investments_test
  pool: 5
  username: investments
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: investments_production
  pool: 5
  username: investments
  password: password